//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LICENSE AGREEMENT: THIS LICENSE AGREEMENT IS A LEGAL AGREEMENT BETWEEN YOU AND EA" +
            "SY GIS .NET FOR EASY GIS .NET DESKTOP EDITION. BY USING THIS PRODUCT YOU  AGREE " +
            "TO BE BOUND BY THE TERMS OF THIS AGREEMENT.\r\n\r\nTHIS SOFTWARE IS PROTECTED BY AUS" +
            "TRALIAN AND INTERNATIONAL COPYRIGHT LAWS.\r\nTHIS SOFTWARE IS LICENSED, NOT SOLD.\r" +
            "\n\r\nGRANTED RIGHTS: THIS LICENSE GRANTS YOU THE RIGHT TO USE THIS SOFTWARE FOR US" +
            "E AS IS OR IN DERIVED SOFTWARE APPLICATIONS, INCLUDING COMMERCIAL DESKTOP  APPLI" +
            "CATIONS.\r\n\r\nLIMITATIONS: YOU MAY NOT REVERSE ENGINEER, DECOMPILE, OR DISASSEMBLE" +
            " EASY GIS .NET DESKTOP EDITION OR ANY OF ITS COMPONENT LIBRARIES, INCLUDING EGIS" +
            ".CONTROLS.DLL  AND EGIS.SHAPEFILELIB.DLL BINARIES. YOU MAY NOT RENT OR LEASE THI" +
            "S SOFTWARE, YOU MAY NOT TRANSFER YOUR RIGHTS UNDER THIS LICENSE AGREEMENT. EASY " +
            "GIS .NET  DESKTOP EDITION MAY NOT BE USED IN A WEB ENVIRONMENT, IT IS SPECIFIC T" +
            "O NON WEB BASED USAGE SCENARIOS. EASY GIS .NET DESKTOP EDITION IS NOT A WEB DEVE" +
            "LOPMENT  TOOL AND MAY NOT BE USED IN A WEB SERVER ENVIRONMENT, THE EASY GIS .NET" +
            " WEB EDITION WOULD BE REQUIRED FOR SUCH A CASE. EASY GIS .NET MAY NOT BE INTEGRA" +
            "TED WITH  OR INCORPORATED INTO ANY SOFTWARE PRODUCT SOLD OR OFFERED TO ANY 3RD P" +
            "ARTY WITHOUT AGREEMENT TO THE REDISTRIBUTION TERMS OF THE EASY GIS .NET DESKTOP " +
            " EDITION OUTLINED BELOW.\r\n\r\nREDISTRIBUTION TERMS:  DEVELOPERS ARE FREE TO DISTRI" +
            "BUTE THE EASY GIS .NET DESKTOP EDITION  EGIS.CONTROLS.DLL AND EGIS.SHAPEFILELIB." +
            "DLL BINARIES \"ROYALTY FREE\"  WITH THEIR APPLICATIONS, INCLUDING COMMERICAL DEVEL" +
            "OPEMENT APPLICATIONS, ONLY WHEN ALL OF THE FOLLOWING TERMS ARE MET:\r\n1) A COPY O" +
            "F THIS LICENCE AGREEMNET IS INCLUDED WITH YOUR APPLICATION.\r\n2) YOUR APPLICATION" +
            " MAY NOT, IN THE OPINION OF EASY GIS .NET, DIRECTLY COMPETE WITH EASY GIS .NET.\r" +
            "\n3) YOU AGREE TO INDEMNIFY, HOLD HARMLESS, AND DEFEND EASY GIS .NET. FROM AND AG" +
            "AINST ANY AND ALL CLAIMS OR LAWSUITS THAT RESULT FROM THE USE OR DISTRIBUTION OF" +
            "  YOUR APPLICATION.\r\n\r\n\r\nDISCLAIMER OF WARRANTY: EASY GIS .NET DESKTOP SOFTWARE " +
            "IS PROVIDED UNDER THIS LICENSE ON AN \"AS IS\" BASIS, WITHOUT WARRANTY OF ANY KIND" +
            ", EITHER EXPRESSED OR  IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES THAT T" +
            "HE SOFTWARE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE OR NO" +
            "N-INFRINGING. THE  ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE SOFTWARE" +
            " IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT C" +
            "ORPORATE EASY  GIS .NET) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR C" +
            "ORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS LIC" +
            "ENSE. \r\n\r\nLIABILITY: IN NO EVENT SHALL CORPORATE EASY GIS .NET BE LIABLE FOR ANY" +
            " DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS" +
            " PROFITS,  BUSINESS INTERRUPTION, LOSS OF INFORMATION OR ANY OTHER PECUNIARY LOS" +
            "S) ARISING OUT OF THE USE OF INABILITY TO USE THIS SOFTWARE, EVEN IF CORPORATE E" +
            "ASY GIS .NET  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\r\n\r\nOWNERSHIP:" +
            " EASY GIS .NET RETAINS OWNERSHIP OF THE SOFTWARE.\r\n\r\nTERMINATION: WITHOUT PREJUD" +
            "ICE TO ANY OTHER RIGHTS, EASY GIS .NET MAY TERMINATE THIS LICENSE AGREEMENT IF Y" +
            "OU FAIL TO COMPLY WITH THE TERMS AND CONDITIONS OF  THIS AGREEMENT. IN SUCH EVEN" +
            "T, YOU MUST DESTROY ALL COPIES OF EASY GIS .NET, ANY DERIVATIVE WORK, AND ALL OF" +
            " ITS COMPONENT PARTS.\r\n\r\nGENERAL: BY USING THIS SOFTWARE YOU ACKNOWLEDGE THAT YO" +
            "U HAVE READ THIS LICENSE AGREEMENT, UNDERSTAND IT, AND AGREE TO BE BOUND BY ITS " +
            "TERMS AND  CONDITIONS.\r\n")]
        public string LicenceText {
            get {
                return ((string)(this["LicenceText"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjects"]));
            }
            set {
                this["RecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LicenceAccepted {
            get {
                return ((bool)(this["LicenceAccepted"]));
            }
            set {
                this["LicenceAccepted"] = value;
            }
        }
    }
}
